# Generated by Django 4.1.2 on 2022-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_branch_delete_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transit_num',
            field=models.IntegerField(),
        ),
    ]
