# Generated by Django 4.1.2 on 2022-10-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_branch_capacity_alter_branch_transit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.IntegerField(blank=True),
        ),
    ]
