# Generated by Django 4.1.2 on 2022-10-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_alter_branch_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
