# Generated by Django 4.1.2 on 2022-11-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0005_branch_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='inst_num',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='swift',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='admin@utoronto.ca', max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transit_num',
            field=models.CharField(max_length=200),
        ),
    ]
