# Generated by Django 4.1.3 on 2022-11-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_bank_owner_alter_bank_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='swift',
            new_name='swift_code',
        ),
    ]
