# Generated by Django 4.1.3 on 2022-11-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_rename_swift_bank_swift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
